import { CaseSensitive, Equal, ArrowRightToLine, Search, WholeWord, X } from 'lucide-react'
import type { ReactNode } from 'react'
import type { SearchOptions } from '../utils/workspace'
export function ToolButton({ label, active = false, onClick, children, disabled = false }: { label: string; active?: boolean; onClick: () => void; children: ReactNode; disabled?: boolean }): React.JSX.Element {
  return <button type="button" className="companion-tool" data-tooltip={label} aria-label={label} aria-pressed={active} disabled={disabled} onClick={onClick}>{children}</button>
}
export function CompanionSearch({ value, onChange, placeholder = 'Search strings…', label = 'Search strings', toolbar, scope = true }: { value: SearchOptions; onChange: (value: SearchOptions) => void; placeholder?: string; label?: string; toolbar?: ReactNode; scope?: boolean }): React.JSX.Element {
  return <div className="companion-search-row"><div className="companion-search"><Search size={14} />{scope && <select aria-label={`${label} scope`} value={value.scope} onChange={event => onChange({ ...value, scope: event.target.value as SearchOptions['scope'] })}><option value="all">Everything</option><option value="source">Source</option><option value="target">Target</option></select>}<input aria-label={label} placeholder={placeholder} value={value.query} onChange={event => onChange({ ...value, query: event.target.value })} />{value.query && <button className="companion-tool" aria-label={`Clear ${label.toLowerCase()}`} onClick={() => onChange({ ...value, query: '' })}><X size={12} /></button>}<div className="companion-search-options"><ToolButton label="Match case" active={value.matchCase} onClick={() => onChange({ ...value, matchCase: !value.matchCase })}><CaseSensitive size={15} /></ToolButton><ToolButton label="Whole word" active={value.wholeWord} onClick={() => onChange({ ...value, wholeWord: !value.wholeWord })}><WholeWord size={14} /></ToolButton></div></div><div className="companion-toolbar"><ToolButton label="Exact match" active={value.exact} onClick={() => onChange({ ...value, exact: !value.exact })}><Equal size={15} /></ToolButton><ToolButton label="Starts with" active={value.startsWith} onClick={() => onChange({ ...value, startsWith: !value.startsWith })}><ArrowRightToLine size={15} /></ToolButton>{toolbar}</div></div>
}
