import { MonitorCog, Search } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useTranslationSession } from '@/context/TranslationSession'
import { getDialogueGroups } from '@/data/dialogReference'
import { cn } from '@/lib/utils'
const GROUPS = ['All', 'Main Menu', 'Settings', 'Audio', 'Interface', 'Accessibility', 'HUD', 'Gameplay'] as const
type Group = typeof GROUPS[number]
const RULES: Record<Exclude<Group, 'All'>, RegExp> = { 'Main Menu': /main menu|title screen|load game|new game|quit/i, Settings: /settings|options|preferences|configuration/i, Audio: /audio|volume|sound|music|voice/i, Interface: /interface|keyboard|controller|mouse|display|video/i, Accessibility: /accessibility|subtitles|colour blind|color blind|text size/i, HUD: /hud|hotbar|tooltip|action bar|portrait/i, Gameplay: /gameplay|difficulty|tutorial|combat|turn based/i }
export function GameInterfacePage(): React.JSX.Element {
  const session = useTranslationSession(); if (session.phase !== 'loaded') return <div className="flex h-full items-center justify-center p-8 text-center"><div className="rounded-xl border border-[#1f2329] bg-[#131518] p-8"><MonitorCog className="mx-auto mb-3 text-cyan-300" size={28} /><h1 className="mb-2 text-lg font-semibold">Game Interface</h1><p className="text-sm text-neutral-500">Load a localization XML in Translate first.</p></div></div>
  const [group, setGroup] = useState<Group>('All'); const [input, setInput] = useState(''); const [query, setQuery] = useState(''); const [selectedId, setSelectedId] = useState<string | null>(null)
  const interfaceEntries = useMemo(() => session.entries.filter((entry) => getDialogueGroups(entry.source).length === 0 && (Object.values(RULES).some((rule) => rule.test(entry.source)) || /mainmenu|settings|interface|audio|hud/i.test(entry.uid))), [session.entries])
  const filtered = useMemo(() => interfaceEntries.filter((entry) => { const inGroup = group === 'All' || RULES[group].test(entry.source); const q = query.trim().toLocaleLowerCase(); return inGroup && (!q || `${entry.source} ${entry.uid}`.toLocaleLowerCase().includes(q)) }).slice(0, 300), [interfaceEntries, group, query])
  const selected = filtered.find((entry) => entry.rowId === selectedId) ?? filtered[0]
  return <div className="flex h-full min-h-0 flex-col bg-[#0c0d0f] text-neutral-200"><div className="flex shrink-0 items-center gap-3 border-b border-[#1f2329] px-5 py-3"><MonitorCog size={20} className="text-cyan-300" /><div><h1 className="text-base font-semibold">Game Interface</h1><p className="text-xs text-neutral-500">{filtered.length} UI strings · menu, settings, audio and HUD</p></div></div><div className="grid min-h-0 flex-1 grid-cols-[minmax(300px,0.48fr)_minmax(0,0.52fr)]"><aside className="flex min-h-0 flex-col border-r border-[#1f2329] p-3"><div className="mb-2 flex gap-2 rounded border border-[#2a2f37] bg-[#131518] px-2 py-1.5"><Search size={14} className="text-neutral-600" /><input value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') setQuery(input) }} placeholder="Type then press Enter..." className="w-full bg-transparent text-xs outline-none placeholder:text-neutral-600" /><button type="button" onClick={() => setQuery(input)} className="rounded bg-cyan-500/10 px-2 text-[10px] text-cyan-300">Search</button></div><div className="mb-3 flex flex-wrap gap-1">{GROUPS.map((item) => <button key={item} type="button" onClick={() => setGroup(item)} className={cn('rounded px-2 py-1 text-[10px]', group === item ? 'bg-cyan-500/15 text-cyan-300' : 'text-neutral-500 hover:bg-[#1c1f24]')}>{item}</button>)}</div><div className="icosa-scroll min-h-0 flex-1 space-y-1 overflow-y-auto">{filtered.map((entry) => <button key={entry.rowId} type="button" onClick={() => setSelectedId(entry.rowId)} className={cn('w-full rounded border px-2 py-2 text-left', selected?.rowId === entry.rowId ? 'border-cyan-400/30 bg-cyan-500/10' : 'border-transparent hover:bg-[#131518]')}><div className="truncate text-xs text-neutral-200">{entry.source}</div><div className="mt-1 truncate font-mono text-[9px] text-neutral-600">{entry.uid}</div></button>)}</div></aside><main className="min-h-0 overflow-y-auto p-5">{selected ? <div className="rounded-lg border border-[#1f2329] bg-[#131518] p-4"><div className="mb-3 text-[10px] font-semibold uppercase tracking-[0.08em] text-cyan-300">Source EN</div><div className="mb-4 text-sm leading-6 text-neutral-200">{selected.source}</div><div className="mb-2 text-[10px] font-semibold uppercase tracking-[0.08em] text-amber-500/70">Translation · {session.targetLang.toUpperCase()}</div><textarea defaultValue={selected.target} onBlur={(event) => session.updateEntry(selected.rowId, event.target.value)} rows={5} className="w-full resize-y rounded border border-[#2a2f37] bg-[#0c0d0f] px-3 py-2 text-sm text-neutral-200 outline-none focus:border-amber-500/60" /><div className="mt-3 rounded border border-cyan-400/20 bg-cyan-500/5 p-3 font-mono text-[10px] text-cyan-200">contentuid: {selected.uid}</div></div> : <p className="text-sm text-neutral-500">No interface strings found in this XML.</p>}</main></div></div>
}
